trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: "230daf6a-03de-4123-9ebd-d342ba614a90"
  imageRepository: "elasticsearch"
  containerRegistry: "ai2ccohort04rcmregistry.azurecr.io"
  dockerfilePath: "$(Build.SourcesDirectory)/elasticsearch/Dockerfile"
  tag: "$(Build.BuildId)"
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build
  jobs:
  - job: Build
    displayName: Build Elasticsearch
    steps:
    - task: Docker@2
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

- stage: Deploy
  displayName: Deploy
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: Deploy Elasticsearch
    steps:
    - script: |
        #!/bin/bash
        set -e
        cd TerraformFolder # Path to your Terraform configuration
        
        # Authenticate to Azure
        az login --service-principal -u $(servicePrincipalId) -p $(servicePrincipalKey) --tenant $(tenantId)
        az account set --subscription $(subscriptionId)

        # Initialize Terraform
        terraform init

        # Apply Terraform changes
        terraform apply -auto-approve
      displayName: Deploy
