trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  SUBSCRIPTION_ID: "4131058a-f1d5-4ad6-a56a-e40fe16303e5"
  RESOURCE_GROUP: "ai2c-cohort-04-rocket-chat-resource-group"
  REGISTRY_NAME: "ai2ccohort04rcmregistry"
  IMAGE: "elasticsearch"
  DOCKERFILE: "$(Build.SourcesDirectory)/elasticsearch/Dockerfile"

stages:
- stage: Build
  displayName: Build
  jobs:
  - job: Build
    displayName: "Build Elasticsearch"
    steps:
    - task: Docker@2
      inputs:
        command: "build"
        dockerfile: "$(DOCKERFILE)"
        repository: "$(IMAGE)"
        containerRegistry: "$(REGISTRY_NAME)"
        tags: |
          "latest"

- stage: Release
  displayName: Release
  dependsOn: Build
  jobs:
  - job: Release
    displayName: Release Elasticsearch
    steps:
    - task: Docker@2
      inputs:
        command: push
        repository: "$(IMAGE)"
        containerRegistry: "$(REGISTRY_NAME)"
        tags: |
          "latest"

- stage: Deploy
  displayName: Deploy
  dependsOn: Release
  jobs:
  - job: Deploy
    displayName: Deploy Elasticsearch
    steps:
    - script: |
        #!/bin/bash
        set -e
        cd TerraformFolder # Path to your Terraform configuration
        
        # Authenticate to Azure
        az login --service-principal -u $(servicePrincipalId) -p $(servicePrincipalKey) --tenant $(tenantId)
        az account set --subscription $(subscriptionId)

        # Initialize Terraform
        terraform init

        # Apply Terraform changes
        terraform apply -auto-approve
      displayName: Deploy
