# Reference
# https://www.elastic.co/guide/en/kibana/current/settings.html

# Kibana-specific settings
server:
  host: "localhost"

# Kibana-to-Elasticsearch communication
elasticsearch:
  hosts: [ "https://localhost:9200" ]
  ssl:
    certificateAuthorities: config/ca.crt
    certificate: config/certs/kibana.crt
    key: config/certs/kibana.key
  username: "${ELASTICSEARCH_USERNAME}"
  password: "${ELASTICSEARCH_PASSWORD}"